version: "3"

services:
  app:
    build: .
    environment:
      GIN_MODE: "release"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_PORT: "${DB_PORT}"
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "${API_PORT}:8080"
    command: go run main.go
